/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jflexp;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTree;
import javax.swing.SwingConstants;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author User
 */
public class Guide extends javax.swing.JFrame {

    private Frame ff;
    private int f;

    public Guide(Frame frame) {
        initComponents();
        this.setTitle("Guida");
        f = 0;
        try {
            this.setIconImage(ImageIO.read(new File(Frame.class.getProtectionDomain().getCodeSource().getLocation().getPath() + "../../Icons/guide.png")));
            Image foto = ImageIO.read(new File(Frame.class.getProtectionDomain().getCodeSource().getLocation().getPath() + "../../Icons/frecciaD.png"));
            foto = foto.getScaledInstance(this.FrecciaD.getWidth(), this.FrecciaD.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon icona = new ImageIcon(foto);
            FrecciaD.setIcon(icona);
            validate();
            foto = ImageIO.read(new File(Frame.class.getProtectionDomain().getCodeSource().getLocation().getPath() + "../../Icons/frecciaS.png"));
            foto = foto.getScaledInstance(this.FrecciaS.getWidth(), this.FrecciaS.getHeight(), Image.SCALE_DEFAULT);
            icona = new ImageIcon(foto);
            FrecciaS.setIcon(icona);
            validate();
        } catch (IOException ex) {
            Logger.getLogger(VelNP.class.getName()).log(Level.SEVERE, null, ex);
        }
        ff = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        Benvenuti = new javax.swing.JPanel();
        Benvenuto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Interfaccia = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FrecciaD = new javax.swing.JButton();
        FrecciaS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Guida");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Benvenuto");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Interfaccia");
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 570));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout());

        Benvenuti.setBackground(new java.awt.Color(255, 255, 255));
        Benvenuti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Benvenuti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Benvenuto.setBackground(new java.awt.Color(255, 255, 255));
        Benvenuto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Benvenuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Benvenuto.setText("Benvenuto ");
        Benvenuto.setOpaque(true);
        Benvenuti.add(Benvenuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manuale generale\n");
        Benvenuti.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 580, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html><p>RunPP 2008 Versione 1.0.0 è l’interfaccia utente per l’esecuzione dei Post-Processor sviluppati da ..., essa consente la multiselezione dei file formato aptsource generati dal CAM di CATIA.<br><br>L'applicazione può essere eseguita su qualunque computer Windows affinchè abbia installato Java <br>Importante non spostare i file all'interno della cartella del programma!<br><br>Se si vuole spostare sul Desktop o in un'altra cartella l'eseguibile del programma creare il collegamento e spostare quello dove si vuole\n.<br><br><br> Contatti: <br> Gianni Yenque: gyenque@gmail.com<br> Vittorio Cortosi: vittorioc2198@icloud.com <br> Andrea Izzo: andreaizzoo99@gmail.com </p></html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Benvenuti.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 570, 200));

        jPanel2.add(Benvenuti, "card4");

        Interfaccia.setBackground(new java.awt.Color(255, 255, 255));
        Interfaccia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Interfaccia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Interfaccia");
        Interfaccia.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, 40));

        jLabel4.setText("<html> \n<p>\nIl programma è strutturato a bottoni, ognuno di essi avrà una propria funzione: \n<br>\n<br>\n    File: Al suo click si potrà caricare uno o più file aptsource presenti nella macchina.\n<br><br>   Save: Servirà a definire la cartella di destinazione del nostro file di output (se non viene definita il file verrà salvato nella cartella del programma).\n<br><br> Run: Avvia la compilazione e creazione del nostro file.\n<br><br> Config: Servirà a dare le configurazione come numero programma e velocità massima (se non definito sarà uguale a 0).\n<br><br> Preview: Editor di testo per la modifica del file aptsource caricato.\n<br> \n<br>\nIn mezzo al nostro programma sarà presente una lista coi file caricato, se viene caricato solo un file verrà selezionato automaticamente quello per gli utilizzi, se più file bisognerà selezionare quale file utilizzare, se nessuno verrà mostrato un avviso che manca il file.\n\n</p>\n</html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Interfaccia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 570, 490));

        jPanel2.add(Interfaccia, "card3");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 590, 570));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrecciaD.setBorderPainted(false);
        FrecciaD.setContentAreaFilled(false);
        FrecciaD.setDefaultCapable(false);
        FrecciaD.setFocusPainted(false);
        FrecciaD.setFocusable(false);
        FrecciaD.setRequestFocusEnabled(false);
        FrecciaD.setRolloverEnabled(false);
        FrecciaD.setVerifyInputWhenFocusTarget(false);
        FrecciaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrecciaDMouseClicked(evt);
            }
        });
        FrecciaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrecciaDActionPerformed(evt);
            }
        });
        jPanel1.add(FrecciaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 20, 30));

        FrecciaS.setBorderPainted(false);
        FrecciaS.setContentAreaFilled(false);
        FrecciaS.setDefaultCapable(false);
        FrecciaS.setFocusPainted(false);
        FrecciaS.setFocusable(false);
        FrecciaS.setRequestFocusEnabled(false);
        FrecciaS.setRolloverEnabled(false);
        FrecciaS.setVerifyInputWhenFocusTarget(false);
        FrecciaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrecciaSMouseClicked(evt);
            }
        });
        FrecciaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrecciaSActionPerformed(evt);
            }
        });
        jPanel1.add(FrecciaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrecciaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrecciaDActionPerformed

    }//GEN-LAST:event_FrecciaDActionPerformed

    private void FrecciaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrecciaSActionPerformed

    }//GEN-LAST:event_FrecciaSActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) this.jTree1
                .getLastSelectedPathComponent();
        String selectedNodeName = selectedNode.toString();
        switch (selectedNodeName) {
            case "Benvenuto":
                this.jPanel2.removeAll();
                jPanel2.repaint();
                jPanel2.revalidate();
                jPanel2.add(Benvenuti);
                this.Benvenuti.setVisible(true);
                this.Interfaccia.setVisible(false);
                this.jLabel1.setVisible(true);
                this.jLabel2.setVisible(true);
                this.jLabel3.setVisible(false);
                this.jLabel4.setVisible(false);
                f = 0;
                break;
            case "Interfaccia":
                this.jPanel2.removeAll();
                jPanel2.repaint();
                jPanel2.revalidate();
                jPanel2.add(Interfaccia);
                this.jLabel3.setVisible(true);
                this.jLabel4.setVisible(true);
                this.Benvenuti.setVisible(false);
                this.jLabel1.setVisible(false);
                this.jLabel2.setVisible(false);
                f = 1;
                break;
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ff.setGuide();
    }//GEN-LAST:event_formWindowClosed

    private void FrecciaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrecciaSMouseClicked
        if (f == 0) {
            this.jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            jPanel2.add(Interfaccia);
            this.jLabel3.setVisible(true);
            this.jLabel4.setVisible(true);
            this.Benvenuti.setVisible(false);
            this.jLabel1.setVisible(false);
            this.jLabel2.setVisible(false);
            f = 1;
        } else if (f == 1) {
            this.jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            jPanel2.add(Benvenuti);
            this.Benvenuti.setVisible(true);
            this.Interfaccia.setVisible(false);
            this.jLabel1.setVisible(true);
            this.jLabel2.setVisible(true);
            this.jLabel3.setVisible(false);
            this.jLabel4.setVisible(false);
            f = 0;
        }
    }//GEN-LAST:event_FrecciaSMouseClicked

    private void FrecciaDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrecciaDMouseClicked
        if (f == 1) {
            this.jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            jPanel2.add(Benvenuti);
            this.Benvenuti.setVisible(true);
            this.Interfaccia.setVisible(false);
            this.jLabel1.setVisible(true);
            this.jLabel2.setVisible(true);
            this.jLabel3.setVisible(false);
            this.jLabel4.setVisible(false);
            f = 0;
        } else if (f == 0) {
            this.jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            jPanel2.add(Interfaccia);
            this.jLabel3.setVisible(true);
            this.jLabel4.setVisible(true);
            this.Benvenuti.setVisible(false);
            this.jLabel1.setVisible(false);
            this.jLabel2.setVisible(false);
            f = 1;

        }
    }//GEN-LAST:event_FrecciaDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Benvenuti;
    private javax.swing.JLabel Benvenuto;
    private javax.swing.JButton FrecciaD;
    private javax.swing.JButton FrecciaS;
    private javax.swing.JPanel Interfaccia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
