
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 11 19:01:20 CEST 2018
//----------------------------------------------------

package jflexp.generated_sources;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OFF = 25;
  public static final int RPAREN = 15;
  public static final int LOADTL = 19;
  public static final int GOTO = 2;
  public static final int SLASH = 4;
  public static final int OUTTOL = 24;
  public static final int ON = 13;
  public static final int CIRCLE = 11;
  public static final int SWITCH = 20;
  public static final int FEDRAT = 7;
  public static final int LPAREN = 14;
  public static final int INTOL = 23;
  public static final int GOFWD = 10;
  public static final int INDIRV = 8;
  public static final int COMMA = 5;
  public static final int MMPR = 27;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int TOOLNO = 3;
  public static final int CUTTER = 18;
  public static final int error = 1;
  public static final int TURN = 26;
  public static final int LINE = 12;
  public static final int TLON = 9;
  public static final int CUTCOM = 17;
  public static final int COOLNT = 16;
  public static final int REWIND = 22;
  public static final int RAPID = 21;
  public static final int SPINDL = 6;
}

